const COMMANDS ={
    FREEHAND : "FREEHAND",
    ERASER:"ERASER",
    UNDO:"UNDO",
    REDO:"REDO",
    DOWNLOAD:"DOWNLOAD",
    ZOOMIN:"ZOOMIN",
    ZOOMOUT:"ZOOMOUT",
    ZOOMEXTENT:"ZOOMEXTENT",
    LINE:"LINE",
    CIRCLE:"CIRCLE",
    RECTANGLE:"RECTANGLE",
    ELLIPSE:"ELLIPSE",
    TEXT:"TEXT",
    PAN:"PAN"

}


export {COMMANDS};